import { access, readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root=fileURLToPath(new URL('../',import.meta.url));
const site=join(root,'site');
for(const file of ['index.html','app.js','book-overview.js','guide-literary-mode.js','translation-compare.js','personal-reference-ui.js','search-worker.js','styles.css','sw.js','manifest.webmanifest','core/domain/references/index.js','core/persistence/index.js']) await access(join(site,file));
try { await access(join(site,'data/bsb/display/PHP/PHP2.json')); } catch { await access(join(site,'data/bsb/display/PHP/PHP2.jsonl')); }
await access(join(site,'data/web/display/PHP/PHP2.json'));
const html=await readFile(join(site,'index.html'),'utf8');
const app=await readFile(join(site,'app.js'),'utf8');
const css=await readFile(join(site,'styles.css'),'utf8');
const bookOverview=await readFile(join(site,'book-overview.js'),'utf8');
const literaryModeUi=await readFile(join(site,'guide-literary-mode.js'),'utf8');
const personalReferenceUi=await readFile(join(site,'personal-reference-ui.js'),'utf8');
const claimsUi=await readFile(join(site,'interpretation-claims.js'),'utf8');
const searchWorkspace=await readFile(join(site,'search-workspace.js'),'utf8');
const a11yOverlays=await readFile(join(site,'a11y-overlays.js'),'utf8');
const translationCompare=await readFile(join(site,'translation-compare.js'),'utf8');
const searchWorker=await readFile(join(site,'search-worker.js'),'utf8');
if(/\bToday\b|dashboard|streak/i.test(html)) throw new Error('Study UI regressed toward dashboard/productivity concepts');
if(html.includes('id="scripture" aria-live')||!html.includes('id="passageStatus" role="status"')||!html.includes('id="saveState" role="status"')||!html.includes('id="toast" role="status" aria-live="polite" aria-atomic="true"')||!html.includes('id="noteDialog" aria-labelledby="noteDialogTitle"')||!html.includes('id="studiesDrawer" role="dialog" aria-modal="true"')||!html.includes('id="reviewDrawer" role="dialog" aria-modal="true"')) throw new Error('Accessibility semantics regressed');
if(!html.includes('class="skip-links"')||!html.includes('href="#biblePane"')||!html.includes('href="#studyPane"')||!html.includes('<h1 class="sr-only">Selah Bible study workspace</h1>')||!html.includes('id="biblePane" aria-label="Scripture" tabindex="-1"')||!html.includes('id="studyPane" aria-label="Study tools" tabindex="-1"')) throw new Error('Skip navigation regressed');
if(!html.includes('id="mobileStudyToggle"')||!html.includes('aria-controls="studyPane"')||!a11yOverlays.includes('mobileSheetController')) throw new Error('Mobile study sheet control regressed');
if(!a11yOverlays.includes('child.inert=mobile&&!open')||!a11yOverlays.includes("setAttribute('aria-hidden','true')")) throw new Error('Collapsed mobile study content must become inert');
if(!css.includes('.selection-menu button{min-height:44px')||!css.includes('.tab{height:44px;min-height:44px')) throw new Error('Mobile touch-target styling regressed');
if(!html.includes('data-tab="claims"')||!html.includes('id="exportClaims"')) throw new Error('Claims tab is missing or not exportable');
if(html.indexOf('data-tab="claims"')>html.indexOf('data-tab="synthesis"')) throw new Error('Claims must precede Synthesis in the study workflow');
if(/development fixture|vendoring command/i.test(app)) throw new Error('Developer-only data language leaked into the study UI');
if(/id="referenceInput"[^>]+value="[^"]+"/.test(html)||!app.includes('renderPassageLauncher')) throw new Error('First launch regressed to a hard-coded sample passage');
if(!html.includes('id="scripture"')||!html.includes('data-tab="guide"')) throw new Error('Core study workspace missing');
if(!app.includes('IndexedDbSelahRepository')||!app.includes('PassageGuideService')) throw new Error('Web UI is not wired to Selah core services');
if(!app.includes("from './book-overview.js'")||!bookOverview.includes('bookOverviewContentHtml')) throw new Error('Book overview UI module is not wired into the study archive');
if(!app.includes("from './guide-literary-mode.js'")||!literaryModeUi.includes('modeControlHtml')) throw new Error('Literary-mode Guide UI module is not wired into the study workspace');
if(!app.includes("from './translation-compare.js'")||!translationCompare.includes('createTranslationRegistry')||!translationCompare.includes('comparisonPanelHtml')) throw new Error('Translation comparison UI module is not wired into the study workspace');
if(!app.includes("from './personal-reference-ui.js'")||!personalReferenceUi.includes('connectedReferenceCardHtml')||!personalReferenceUi.includes('personalStudyLinksHtml')||!app.includes('studiesOverlappingPassage')) throw new Error('Personal-reference UI module is not wired into Scripture connections');
if(!app.includes('personalStudyLinksHtml(priorStudies')||!app.includes('Prior studies')) throw new Error('Reference Peek multi-study recall regressed');
if(!personalReferenceUi.includes("new Set()")||!personalReferenceUi.includes("+${remaining} more")) throw new Error('Contextual prior-study recall must deduplicate and expose overflow');
if(!app.includes("new Worker('./search-worker.js'")||!searchWorker.includes('ScriptureSearchIndex')) throw new Error('Scripture search worker is not wired into the deployable study workspace');
if(app.includes("const tokenEls = $('.token');")) throw new Error('Highlight renderer regressed to a single-element token selector');
if(/(?<!\\$)\\$\\([^\\n;]*\\)\\.(?:forEach|map|filter|findIndex|indexOf|some|every|reduce|slice|at)\\b/.test(app)) throw new Error('A single-element DOM helper is used with an array method');
console.log('Static site integrity checks passed.');
